services:
  the-gamers-network-development-database:
    image: postgres:14
    container_name: tgn-development-database
    ports:
      - "5432:5432"
    env_file:
      - "./development.env"
    environment:
      - POSTGRES_DB=TheGamersNetwork
    volumes:
      - database:/var/lib/postgresql

  the-gamers-network-pgadmin:
    image: dpage/pgadmin4
    container_name: tgn-development-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  database:
    driver: local
